### PR TITLE
fix

### PR DESCRIPTION
**Pull request by mallu11**

### CODE REVIEW

**Comment by mallu11** [comment]
Using c:GetSummonLocation()==LOCATION_EXTRA for the monsters like <i>Supreme King Dragon Starving Venom</i>,but if you Special Summon a face-up Pendulum Monster from Extra Deck（it's also a Fusion,Synchro or XYZ Monster）by an effect without using materials,the effect of this card also can activate.

**Comment by mallu11** [comment]
Using "c:GetSummonType()==SUMMON_TYPE_SPECIAL+1" for the monsters like <i>Supreme King Dragon Starving Venom</i>.Must use "aux.AddContactFusionProcedure():SetValue(1)".

**Comment by mallu11** [comment]
add "e2:SetValue(1)" in Auxiliary.AddContactFusionProcedure to mark it's the "EFFECT_SPSUMMON_PROC" which uses the fusion material.

**Comment by mercury233** [comment]
灵摆次元单独开个pr吧

**Comment by mallu11** [comment]
> 灵摆次元单独开个pr吧

开了

**Comment by mallu11** [comment]
> 灵摆次元单独开个pr吧

忘记有神数的神托可以参照了，剩下的应该可以merge了

**Comment by mallu11** [comment]
> 灵摆次元单独开个pr吧

贤石炼金师在对方回合发动的场合，无法自己选择想要除外和特召的怪兽。

**Pull request merged**
