### PR TITLE
Add cards by Lyris

### PR DESCRIPTION
**Pull request by Lyris12**
"Beetrooper Scale Bomber"
"Pazuzule"
"Resurrection Breath"

### CODE REVIEW

**Comment by mercury233** [comment]
Please do NOT use official id in this repo, it will break the whole update progress

**Comment by Lyris12** [comment]
Then why were the official IDs themselves moved from [ygopro-scripts](https://github.com/Fluorohydride/ygopro-scripts)?

**Comment by mercury233** [comment]
The guy (me) who merge them will change the ids

**Comment by Lyris12** [comment]
And so you closed pull with the official/destination/changed IDs in scripts at https://github.com/Fluorohydride/ygopro-scripts/pull/1686 why?

**Comment by mercury233** [comment]
pre-release scripts shouldn't be committed to that repo directly

**Comment by Lyris12** [comment]
Done @mercury233

**Comment by Lyris12** [comment]
+ "Beetrooper Formation"

**Comment by Lyris12** [comment]
+ "Beetrooper Fly & Sting"

**Comment by Lyris12** [comment]
+ "Beetrooper Armor Horn"

**Comment by Lyris12** [comment]
+ "Ra'ten, the Heavenly General"

**Comment by Lyris12** [comment]
+ "Night's End Administrator"

**Comment by Lyris12** [comment]
+"Lost Sanctuary"

**Pull request merged**
