### PR TITLE
Create Parametalfoes Fusion by Xylen09

### PR DESCRIPTION
**Pull request by Xylen09**
c101103061.lua

### CODE REVIEW

**Comment by mercury233** [comment]
_why would it work with this file name_

**Comment by Xylen09** [comment]
> _why would it work with this file name_

sorry i accidentally delete it waitt

**Comment by Xylen09** [comment]
> _why would it work with this file name_

ops'-'

**Comment by mercury233** [comment]
well the file isn't in the correct folder, i'll fix it later.

but the "using up to 1 monster each from" limit seems not implemented?

**Comment by Xylen09** [comment]
> well the file isn't in the correct folder, i'll fix it later.
> 
> but the "using up to 1 monster each from" limit seems not implemented?

yeh but added merge to use a face material from the Extra Deck

**Comment by mercury233** [comment]
I mean, you shouldn't use all materials from extra deck, but your script didn't check it

**Comment by Xylen09** [comment]
and also sorry im just new in github :p hehe

**Pull request merged**
