### PR TITLE
Fix for Vermillion Dragon Mech (Already Fixed)

### PR DESCRIPTION
**Pull request by YGO5upp0r73r**
[The effect reads](http://yugioh.wikia.com/wiki/Vermillion_Dragon_Mech),
> **If** this Synchro Summoned card is destroyed by card effect and sent to the Graveyard: **You** can...

I'm new to YGOPRO's scripting standards, but `EVENT_TO_GRAVE` can miss timing, correct? If it can, then according to constant.lua, if I translated it correctly, adding `EFFECT_FLAG_DELAY` is necessary.
Also, correct me if I'm wrong, but the effect doesn't exclude the Damage Step, so a flag for that is necessary to add as well, isn't it?

Edit comment: I think these flags are necessary, according to these, unless YGOPRO's source code updated and `EVENT_TO_GRAVE` covers those flags now...
[Archfiend Cavalry](http://yugioh.wikia.com/wiki/Archfiend_Cavalry): https://github.com/Fluorohydride/ygopro-scripts/blob/master/c92039899.lua#L7
[Mermail Abysslinde](Mermail Abysslinde): https://github.com/Fluorohydride/ygopro-scripts/blob/master/c23899727.lua#L8

### CODE REVIEW

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro/commit/a10d8c56e602c1ca23eade839c5586fad8dca122 `EFFECT_TYPE_SINGLE` + `EVENT_TO_GRAVE`/`EVENT_DESTROYED`/`EVENT_SPSUMMON_SUCCESS`/`EVENT_TO_HAND` can be activated in damage step by default.

**Comment by YGO5upp0r73r** [comment]
@nekrozar Arigatou.

**Comment by nekrozar** [comment]
@YGO5upp0r73r `EFFECT_FLAG_DELAY` is also needed...
https://github.com/Fluorohydride/ygopro-pre-script/commit/eda941aee4912270ebc7883cf60f9a7ad36bd0ff Fixed. Thank you.

**Comment by YGO5upp0r73r** [comment]
@nekrozar No problem.

It's easy to overlook Damage Step-related effects. In my experience, the Damage Step and its rulings is one of the more complicated mechanics in the game.

**Pull request closed without merging**
