### PR TITLE
Added scripts for SD38-JP

### PR DESCRIPTION
**Pull request by XGlitchy30**
Scripted the following cards:
-- Cerulean Sky Fire (ID: 100338019)
-- Hyper Blaze (ID: 100338034)

### CODE REVIEW

**Comment by mercury233** [comment]
I prefer to modify the script of the monster to update the summon proc

**Comment by XGlitchy30** [comment]
> 
> 
> I prefer to modify the script of the monster to update the summon proc

Understood. Should I entirely remove the "proc effects" from those 2 scripts and open a new pull request with the updated files? Or do you want to deal with it by yourself?

**Comment by mercury233** [comment]
I can do it later, thank you for the scripts

**Comment by XGlitchy30** [comment]
Gotcha

**Pull request merged**
