### PR TITLE
April VJump archetypes

### PR DESCRIPTION
**Pull request by EerieCode**
I've added all new archetypes revealed in this month's Jump to the list. Since the "Chaos" archetype is introduced in the Movie Pack, I've exchanged position between it and the "Cardian", in order to keep the proper order: as for "Cyber Angel", of course, is a subarchetype of "Cyber". Any objections?

### CODE REVIEW

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-scripts/pull/374
I think Chaos is 0x10cf.
Because Black Luster Soldier japanese name include Chaos.

**Comment by EerieCode** [comment]
I forgot about that... Okay, I've changed the file appropriately.

**Comment by nekrozar** [comment]
Thank you for your time.
I think Magnet Warrior is `0x2066`.
Because Magnet Warrior japanese name include Warrior.

**Comment by EerieCode** [comment]
Like "Symphonic Warrior", then? In that case, the same should apply for "Magna Warrior" as well. I've updated the file.

**Comment by nekrozar** [comment]
Magna Warrior japanese name doesn't include Warrior.

**Comment by EerieCode** [comment]
Fixed.

**Pull request merged**
