### PR TITLE
add 10 cards about BF in DABL

### PR DESCRIPTION
**Pull request by Corvus1998**

### CODE REVIEW

**Comment by shadowfox87** [comment]
https://forum.duelistsunite.org/t/blackwing-vata-effect-doesnt-work-after-being-searched/12295 @Corvus1998

**Comment by shadowfox87** [comment]
Chinook (101110003) has Shamal (101110002) effect,
Zonda (101110005) has Chinook's effect, but it lets u send any extra deck monsters instead of only BW/BWdragon synchros

**Comment by dammy63** [comment]
Don't forget
add "aux.AddCodeList(c,9012916)" to "c80254726" and "c17465972"

**Comment by shadowfox87** [comment]
Hello, the Token effect of Blackwing Suthri isnt working properly and there is also a bug where you seemingly cant use the effects of Blackwing Vata and/or Blackwing Shamal in the same turn after using one of the just mentioned effects.

**Comment by Corvus1998** [comment]
It runs no problem here with my Suthris script and my cdb file.Are you  sure that you have correct non-tuner BF monsters in your deck and  Black-Winged Dragon in your extra-deck? (Or maybe it’s the problem that I  wrote "SetDescription " in the script???)



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月18日(星期三) 晚上8:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Fluorohydride/ygopro-pre-script] add 10 cards about BF in DABL (PR #956)





 
https://forum.duelistsunite.org/t/blackwing-vata-effect-doesnt-work-after-being-searched/12295 @Corvus1998

**Pull request merged**
