### PR TITLE
add DBAL cards

### PR DESCRIPTION
**Pull request by Trishula9**

### CODE REVIEW

**Comment by Starstrike** [comment]
@Trishula9 

The script for Tearalaments Heartbeats does not appear to work properly. The card can be activated but it just goes to grave. You can't target a card on the field or send a card from hand.

**Comment by Starstrike** [comment]
Tearalaments Scream is also not working as it can't be activated from hand. The effect to add a Tearalaments Trap when its sent to Grave by card effect is also not working.

**Comment by shadowfox87** [comment]
@Trishula9 please let us know if you have read this message by replying. If you can tell me your QQ or discord username, will help.

**Comment by Trishula9** [comment]
> @Trishula9 please let us know if you have read this message by replying. If you can tell me your QQ or discord username, will help.

QQ：31891579

**Comment by shadowfox87** [comment]
@Trishula9 thank you. Please also fix the above scripts based on the bugs that Ryder reported.

**Comment by shadowfox87** [comment]
We found the issue. The scripts have been swapped:

101110057    Tearalaments Heartbeats
101110058    Tearalaments Scream

@Trishula9

**Comment by Trishula9** [comment]
"ナチュル" cards may need to change cost to such as c101110020.spcost to match "ナチュル・カメリア".

**Comment by shadowfox87** [comment]
https://forum.duelistsunite.org/t/right-corner-spell-trap-zone-is-unaffected-by-kshari-la-shangri-las-effect/12655/1 @Trishula9

**Pull request merged**
