### PR TITLE
add AGOV cards

### PR DESCRIPTION
**Pull request by Trishula9**

### CODE REVIEW

**Comment by Trishula9** [comment]
Sorry I didn't implement c101202047.lua. I don't know how to achieve an immediate pendulum summon with an ignition effect

**Comment by Trishula9** [comment]
Known: There are some bugs in the interaction between c101202047.lua's effect ② and other EFFECT_EXTRA_PENDULUM_SUMMON effects.

**Comment by Trishula9** [comment]
Resolved the interaction conflicting bug above

**Comment by Lyris12** [comment]
`Soul of the Supreme Celestial King` causes an OCGCore crash: https://cdn.discordapp.com/attachments/285844671836717057/1116118001301868675/image.png

**Comment by Trishula9** [comment]
I used setname 0x200 as ヴェーダ, 0x201 as ハート and counter 0x67 as ヴェーダ＝ウパニシャッド counter. These numbers can be changed.

**Pull request merged**
